version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: 0.0.8
    schedule:
      interval: "daily"
      time: "08:00"
    reviewers:
      - "seism0saurus"
    groups:
      backend:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/frontend/"
    target-branch: 0.0.8
    schedule:
      interval: "daily"
      time: "10:00"
    reviewers:
      - "seism0saurus"
    groups:
      frontend:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/.github"
    target-branch: 0.0.8
    schedule:
      interval: "daily"
      time: "12:00"
    reviewers:
      - "seism0saurus"

  - package-ecosystem: "docker"
    directory: "/infrastructure/glacier"
    target-branch: 0.0.8
    schedule:
      interval: "daily"
      time: "14:00"
    reviewers:
      - "seism0saurus"
