version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "seism0saurus"
    groups:
      logging:
        patterns:
          - "ch.qos.logback:*"
          - "ch.qos.logback.contrib:*"
          - "com.fasterxml.jackson.core:*"

  - package-ecosystem: "npm"
    directory: "/webapp/angular"
    schedule:
      interval: "daily"
    reviewers:
      - "seism0saurus"
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
      testing:
        patterns:
          - "karma/*"
          - "jasmine-core/*"
          - "@types/jasmine/*"

  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "daily"
    reviewers:
      - "seism0saurus"

  - package-ecosystem: "docker"
    directory: "/containerimage"
    schedule:
      interval: "daily"
    reviewers:
      - "seism0saurus"
