version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: 0.0.5
    schedule:
      interval: "daily"
    reviewers:
      - "seism0saurus"
    groups:
      backend:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/frontend/"
    target-branch: 0.0.5
    schedule:
      interval: "daily"
    reviewers:
      - "seism0saurus"
    groups:
      frontend:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/.github"
    target-branch: 0.0.5
    schedule:
      interval: "daily"
    reviewers:
      - "seism0saurus"

  - package-ecosystem: "docker"
    directory: "/containerimage"
    target-branch: 0.0.5
    schedule:
      interval: "daily"
    reviewers:
      - "seism0saurus"
