package de.seism0saurus.glacier.share.domain;

import java.util.Objects;
import java.util.regex.Pattern;

/**
 * Value object for a share-link identifier.
 *
 * <p>An opaque, URL-safe base64 token of at least 43 characters (≥256 bits entropy
 * when generated by {@code SecureRandomTokenGenerator}). The value is immutable and
 * enforced to be syntactically valid at construction time.
 *
 * <p>The raw ctor is {@code public} here (unlike domain-package-private in the DDD-lane
 * peer's version) because this lane needs to reconstruct instances from HTTP path variables.
 * The peer lane owns the generation path (via {@code SecureRandomTokenGenerator}).
 *
 * <p>Security: ADR-SHARE-01, ADR-SHARE-05 — treated as a session-token-adjacent credential;
 * never logged raw (use {@link de.seism0saurus.glacier.util.LogScrubber#hash8(String)}).
 */
public final class ShareLinkId {

    /** Minimum token length: 43 URL-safe base64 chars ≈ 256 bits. */
    public static final int MIN_LENGTH = 43;

    /** Allowed characters: URL-safe base64 alphabet. */
    private static final Pattern VALID = Pattern.compile("^[A-Za-z0-9_-]{" + MIN_LENGTH + ",}$");

    private final String value;

    /**
     * Constructs a {@link ShareLinkId} from a raw string.
     *
     * @param value the raw token; must be at least {@value MIN_LENGTH} URL-safe base64 chars
     * @throws IllegalArgumentException if the value is null, too short, or contains invalid chars
     */
    public ShareLinkId(final String value) {
        if (value == null || !VALID.matcher(value).matches()) {
            throw new IllegalArgumentException(
                    "Invalid ShareLinkId: must be >= " + MIN_LENGTH + " URL-safe base64 characters");
        }
        this.value = value;
    }

    /** Returns the raw string representation. */
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ShareLinkId other)) return false;
        return value.equals(other.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }
}
