package de.seism0saurus.glacier.share.domain;

import de.seism0saurus.glacier.util.LogScrubber;

import java.util.Objects;
import java.util.regex.Pattern;

/**
 * Value object representing the opaque, URL-safe identifier for a {@link ShareLink}.
 *
 * <p>Wraps a URL-safe base64 string (RFC 4648 §5 alphabet: {@code A-Z a-z 0-9 - _}) of at
 * least 43 characters, providing ≥ 256 bits of entropy when generated by
 * {@link SecureRandomTokenGenerator}.  The 43-character floor comes from
 * ⌈32 bytes × 8 bits / 6 bits per base64url char⌉ = 43.
 *
 * <p>Security design (ADR-SHARE-01):
 * <ul>
 *   <li>The constructor is package-private to prevent callers from constructing IDs
 *       from arbitrary strings — generation must go through {@link SecureRandomTokenGenerator}.</li>
 *   <li>Equality uses {@link Objects#equals} on the token string. The token is not a password
 *       (it appears in the URL), so constant-time comparison is not required here; however,
 *       {@link #hash8()} delegates to {@link LogScrubber#hash8} for log-safe output.</li>
 *   <li>This type is DISTINCT from {@link ShareViewerId} — the compiler prevents cross-use.</li>
 * </ul>
 *
 * @see ShareViewerId
 * @see SecureRandomTokenGenerator
 */
public final class ShareLinkId {

    /**
     * Minimum token length in characters (256 bits of entropy at 6 bits/char in base64url).
     */
    static final int MIN_LENGTH = 43;

    /**
     * Accepts only URL-safe base64 characters (RFC 4648 §5): {@code A-Z a-z 0-9 - _}.
     * Excludes {@code +}, {@code /}, and padding {@code =}.
     */
    private static final Pattern URL_SAFE_BASE64 = Pattern.compile("^[A-Za-z0-9_-]+$");

    private final String token;

    /**
     * Package-visible constructor — use {@link SecureRandomTokenGenerator} for generating new IDs,
     * or {@link #fromUrlPath(String)} for parsing caller-supplied strings.
     *
     * <p>This constructor is package-private to signal that random generation is the preferred path.
     * The {@link #fromUrlPath(String)} factory method exists for web-layer parsing.
     * Tests in the same package ({@code share.domain}) may also call this directly.
     *
     * @param token a URL-safe base64url string of at least {@value MIN_LENGTH} characters
     * @throws IllegalArgumentException if {@code token} is null, blank, too short, or
     *                                  contains characters outside the URL-safe base64url alphabet
     */
    ShareLinkId(final String token) {
        if (token == null || token.isBlank()) {
            throw new IllegalArgumentException("ShareLinkId token must not be null or blank");
        }
        if (token.length() < MIN_LENGTH) {
            throw new IllegalArgumentException(
                    "ShareLinkId token length " + token.length() + " is below the minimum of " + MIN_LENGTH);
        }
        if (!URL_SAFE_BASE64.matcher(token).matches()) {
            throw new IllegalArgumentException(
                    "ShareLinkId token contains characters outside the URL-safe base64url alphabet");
        }
        this.token = token;
    }

    /**
     * Parses a URL path segment string as a {@link ShareLinkId}, performing full validation.
     *
     * <p>Use this factory method in web-layer code when parsing an ID from a URL path variable.
     * Validation is identical to the constructor — invalid strings throw
     * {@link IllegalArgumentException}, which controllers translate to 404 (anti-enumeration).
     *
     * @param raw the URL path segment to parse; must satisfy the base64url + length invariants
     * @return a validated {@link ShareLinkId}
     * @throws IllegalArgumentException if {@code raw} fails validation
     */
    public static ShareLinkId fromUrlPath(final String raw) {
        return new ShareLinkId(raw);
    }

    /**
     * Returns the raw URL-safe base64url token string.
     *
     * <p>Suitable for use as the URL path segment in a share link.
     *
     * @return the raw token; never null or blank
     */
    public String value() {
        return token;
    }

    /**
     * Returns the first 8 hex characters of SHA-256({@code token}) for safe log output.
     *
     * <p>Delegates to {@link LogScrubber#hash8} — consistent with the existing log hygiene
     * discipline for wallIds (D-13, SR-8).  The raw token is NEVER logged directly.
     *
     * @return an 8-character lowercase hex fingerprint; deterministic
     */
    public String hash8() {
        return LogScrubber.hash8(token);
    }

    @Override
    public boolean equals(final Object obj) {
        if (this == obj) return true;
        if (!(obj instanceof ShareLinkId other)) return false;
        return Objects.equals(token, other.token);
    }

    @Override
    public int hashCode() {
        return Objects.hash(token);
    }

    /**
     * Returns the raw token — suitable for embedding in URLs.
     *
     * <p>Do NOT log this value directly; use {@link #hash8()} in log statements.
     *
     * @return the raw token string
     */
    @Override
    public String toString() {
        return token;
    }
}
