package de.seism0saurus.glacier.webservice.messaging.messages;

import de.seism0saurus.glacier.webservice.messaging.HashtagFormat;
import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import net.jqwik.api.Arbitraries;
import net.jqwik.api.Arbitrary;
import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import net.jqwik.api.Provide;
import net.jqwik.api.constraints.StringLength;

import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Property-based fuzz tests for {@link SubscriptionMessage} Bean Validation (SR-FUZZ-11).
 *
 * <p>Uses <a href="https://jqwik.net">jqwik 1.8.4</a> to verify two complementary properties:
 * <ol>
 *   <li>{@link #anyStringNotMatchingPatternIsRejected}: any string that does NOT satisfy
 *       {@link HashtagFormat#PATTERN} must produce at least one Bean Validation violation on
 *       the {@code hashtag} field — confirming that the validation guard is exhaustive.</li>
 *   <li>{@link #anyStringMatchingPatternIsAccepted}: any string that DOES satisfy
 *       {@link HashtagFormat#PATTERN} must pass validation — confirming that the guard
 *       does not over-reject valid hashtags.</li>
 * </ol>
 *
 * <p>SR-FUZZ-11: The pattern referenced in property 1 is {@link HashtagFormat#PATTERN} —
 * the constant itself, not a copy of it. This guarantees that the fuzz test stays in sync
 * with the validation annotation on {@link SubscriptionMessage#getHashtag()} automatically.
 *
 * <p>SR-FUZZ-02: Assertion messages never echo raw arbitrary inputs. Fixed strings are used.
 */
class SubscriptionMessageHashtagFuzzTest {

    /**
     * Lazily-initialised validator, built once per test run via the standard
     * {@link jakarta.validation.Validation} bootstrap. No Spring context required.
     */
    private static final Validator VALIDATOR;

    static {
        VALIDATOR = Validation.buildDefaultValidatorFactory().getValidator();
    }

    // -------------------------------------------------------------------------
    // Property 1: strings outside the pattern must be rejected
    // -------------------------------------------------------------------------

    /**
     * SR-FUZZ-11 property 1: any string that does not match {@link HashtagFormat#PATTERN}
     * must fail Bean Validation — at least one violation must be reported on the
     * {@code hashtag} field.
     *
     * <p>The filter excludes strings that happen to match the pattern, so jqwik only tests
     * strings that are genuinely invalid. This property is exhaustively checked for 500
     * generated inputs.
     *
     * <p>SR-FUZZ-02: The assertion message is a fixed string; raw input is never echoed.
     *
     * @param invalidHashtag a string generated by jqwik that does NOT match
     *                       {@link HashtagFormat#PATTERN}
     */
    @Property(tries = 500)
    void anyStringNotMatchingPatternIsRejected(
            @ForAll @StringLength(min = 0, max = 200) String invalidHashtag) {

        // Skip strings that actually match the pattern — we only want to test invalid ones.
        // (jqwik's filter may generate a few valid strings; they do not invalidate this property.)
        if (invalidHashtag.matches(HashtagFormat.PATTERN)) {
            return;
        }

        SubscriptionMessage message = messageWithHashtag(invalidHashtag);
        Set<ConstraintViolation<SubscriptionMessage>> violations = VALIDATOR.validate(message);

        assertThat(violations)
                .as("Expected invalid hashtag to fail validation")
                .isNotEmpty();
    }

    // -------------------------------------------------------------------------
    // Property 2: strings matching the pattern must be accepted
    // -------------------------------------------------------------------------

    /**
     * SR-FUZZ-11 property 2: any string that satisfies {@link HashtagFormat#PATTERN}
     * must pass Bean Validation — no violations should be reported.
     *
     * <p>The {@code @Provide validHashtags} generator produces strings composed entirely
     * of printable Unicode letters, digits, and underscores, bounded by the pattern's
     * length constraint (1–50 characters).
     *
     * <p>SR-FUZZ-02: The assertion message is a fixed string; raw input is never echoed.
     *
     * @param validHashtag a pattern-conformant string produced by {@link #validHashtags()}
     */
    @Property(tries = 500)
    void anyStringMatchingPatternIsAccepted(@ForAll("validHashtags") String validHashtag) {
        // Pre-condition: the provider must only emit strings matching the pattern.
        // If this fails, the provider itself is the bug.
        assertThat(validHashtag.matches(HashtagFormat.PATTERN))
                .as("Provider emitted a string that does not match the hashtag pattern")
                .isTrue();

        SubscriptionMessage message = messageWithHashtag(validHashtag);
        Set<ConstraintViolation<SubscriptionMessage>> violations = VALIDATOR.validate(message);

        assertThat(violations)
                .as("Expected valid hashtag to pass validation")
                .isEmpty();
    }

    /**
     * Generates arbitrary strings that conform to {@link HashtagFormat#PATTERN}.
     *
     * <p>Strategy: produce strings of 1–50 characters drawn from the Unicode letter,
     * digit, and underscore character classes — the same set that
     * {@code ^[\p{L}\p{N}_]{1,50}$} accepts.
     *
     * <p>SR-FUZZ-11: Uses {@link HashtagFormat#PATTERN} as the verification predicate
     * (in the pre-condition assertion), ensuring the generator stays in sync with the
     * production constant.
     *
     * @return an {@link Arbitrary} producing pattern-conformant hashtag strings
     */
    @Provide
    Arbitrary<String> validHashtags() {
        // Build strings from the allowed character classes using jqwik's combinators.
        // Underscore is included via the explicit char list; letters and digits via alphaNumerics.
        // We combine the two pools and then filter to confirm pattern compliance.
        return Arbitraries.strings()
                // Allow only letter, digit, and underscore code points
                .withChars("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_")
                .ofMinLength(1)
                .ofMaxLength(50)
                .filter(s -> s.matches(HashtagFormat.PATTERN));
    }

    // -------------------------------------------------------------------------
    // Helper
    // -------------------------------------------------------------------------

    /**
     * Creates a {@link SubscriptionMessage} with the given hashtag value.
     *
     * @param hashtag the hashtag to set; may be null or any string
     * @return a configured {@link SubscriptionMessage}
     */
    private static SubscriptionMessage messageWithHashtag(final String hashtag) {
        SubscriptionMessage message = new SubscriptionMessage();
        message.setHashtag(hashtag);
        return message;
    }
}
