package de.seism0saurus.glacier.share.web;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatNoException;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Unit tests for {@link ImageProxyHmacSecretValidator}.
 *
 * <p>Security requirement: SR-SHARE-10 (fail-closed HMAC boot policy).
 * Decision reference: user resolution 2026-04-22 option A — fail-closed in prod,
 * auto-generate with WARN in dev.
 */
class ImageProxyHmacSecretValidatorTest {

    // -----------------------------------------------------------------------
    // Production profile (secureCookies=true) — FAIL CLOSED
    // -----------------------------------------------------------------------

    @Test
    void missingSecretInProd_throwsAtConstruction() {
        // SR-SHARE-10: missing secret in production MUST prevent context startup
        assertThatThrownBy(() -> new ImageProxyHmacSecretValidator(null, true))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("glacier.share.imgproxy.hmacSecret")
                .hasMessageContaining("32 bytes");
    }

    @Test
    void blankSecretInProd_throwsAtConstruction() {
        assertThatThrownBy(() -> new ImageProxyHmacSecretValidator("", true))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("glacier.share.imgproxy.hmacSecret");
    }

    @Test
    void whitespaceOnlySecretInProd_throwsAtConstruction() {
        assertThatThrownBy(() -> new ImageProxyHmacSecretValidator("   ", true))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("glacier.share.imgproxy.hmacSecret");
    }

    @Test
    void shortSecretInProd_throwsAtConstruction() {
        // Minimum 32 bytes — present but too short also throws
        assertThatThrownBy(() -> new ImageProxyHmacSecretValidator("short", true))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("32 bytes");
    }

    @Test
    void exactMinLengthSecretInProd_startsSuccessfully() {
        // Exactly 32 ASCII chars = 32 UTF-8 bytes — just at minimum
        assertThatNoException()
                .isThrownBy(() -> new ImageProxyHmacSecretValidator("A".repeat(32), true));
    }

    @Test
    void adequateLengthSecretInProd_isOperationalAndReturnsSecret() {
        ImageProxyHmacSecretValidator validator =
                new ImageProxyHmacSecretValidator("A".repeat(32), true);
        assertThat(validator.isOperational()).isTrue();
        byte[] secret = validator.getEffectiveSecret();
        assertThat(secret).isNotNull();
        assertThat(secret.length).isGreaterThanOrEqualTo(32);
    }

    // -----------------------------------------------------------------------
    // Dev profile (secureCookies=false) — auto-generate with WARN
    // -----------------------------------------------------------------------

    @Test
    void missingSecretInDev_autoGenerates_noException() {
        // Dev mode: missing secret auto-generates a random one, does not throw
        assertThatNoException()
                .isThrownBy(() -> new ImageProxyHmacSecretValidator(null, false));
    }

    @Test
    void missingSecretInDev_autoGeneratedSecretIsOperational() {
        ImageProxyHmacSecretValidator validator =
                new ImageProxyHmacSecretValidator(null, false);
        assertThat(validator.isOperational()).isTrue();
        byte[] secret = validator.getEffectiveSecret();
        assertThat(secret).isNotNull();
        assertThat(secret.length).isGreaterThanOrEqualTo(32);
    }

    @Test
    void blankSecretInDev_autoGenerates_noException() {
        assertThatNoException()
                .isThrownBy(() -> new ImageProxyHmacSecretValidator("", false));
        ImageProxyHmacSecretValidator validator =
                new ImageProxyHmacSecretValidator("", false);
        assertThat(validator.isOperational()).isTrue();
    }

    @Test
    void shortSecretInDev_acceptedWithWarn() {
        // Dev only: short but present secret is accepted (warn, not throw)
        assertThatNoException()
                .isThrownBy(() -> new ImageProxyHmacSecretValidator("short", false));
        ImageProxyHmacSecretValidator validator =
                new ImageProxyHmacSecretValidator("short", false);
        assertThat(validator.isOperational()).isTrue();
    }

    @Test
    void getEffectiveSecretReturnsCopy_notReference() {
        // Defensive copy: modifying the returned array must not affect internal state
        ImageProxyHmacSecretValidator validator =
                new ImageProxyHmacSecretValidator("A".repeat(32), true);
        byte[] copy1 = validator.getEffectiveSecret();
        copy1[0] = (byte) 0xFF;
        byte[] copy2 = validator.getEffectiveSecret();
        assertThat(copy2[0]).isNotEqualTo((byte) 0xFF);
    }
}
