package de.seism0saurus.glacier.security;

import jakarta.servlet.http.Cookie;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import social.bigbone.MastodonClient;

import java.util.regex.Pattern;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;

/**
 * IT-sec-LEAK: Response-body secret-leak integration test (SR-NEW-03, SR-NEW-05).
 *
 * <p>Verifies that no HTTP response body (except the intentional echo on {@code GET /rest/wall-id})
 * reflects the canary wallId {@code 00000000-0000-0000-0000-000000000001} back to the caller.
 * Also verifies that response bodies never contain stack traces or internal Java/Glacier class
 * references (WSTG-ERRH-01, ASVS V11.1.4 L1).
 *
 * <p><b>Mode coverage (ADR-5)</b>: This test runs in all four Glacier operational modes:
 * <ul>
 *   <li><b>live</b>: default mode, WebSocket active</li>
 *   <li><b>fallback</b>: {@code glacier.fallback.enabled=true} (explicit) — HTTP polling active</li>
 *   <li><b>killswitch</b>: {@code glacier.fallback.enabled=false} — HTTP fallback disabled</li>
 *   <li><b>insecure-transport</b>: {@code glacier.cookie.secure=false} — HTTP transport</li>
 * </ul>
 * Separate nested classes carry mode-specific {@link TestPropertySource} annotations so
 * each mode gets its own Spring application context.
 *
 * <p><b>Canary strategy (ADR-4)</b>: The fixed canary wallId
 * {@code 00000000-0000-0000-0000-000000000001} is injected as the {@code wallId} cookie.
 * It is fixed (not random) so assertions are deterministic and auditable. The canary is
 * intentionally all-zeros with suffix 1 — it will never be generated by
 * {@link java.util.UUID#randomUUID()} in practice.
 *
 * <p>Security reference: C9 — Logging and Monitoring; ASVS V6.2 (L1), V11.1.4 (L1);
 * WSTG-ERRH-01, WSTG-INFO-05.
 */
public class ResponseBodySecretLeakIT {

    // -------------------------------------------------------------------------
    // Constants shared across all nested classes
    // -------------------------------------------------------------------------

    /**
     * Fixed canary wallId. Must not appear in any response body except GET /rest/wall-id.
     * ADR-4: fixed canary for deterministic, auditable assertions.
     */
    static final String CANARY_WALL_ID = "00000000-0000-0000-0000-000000000001";

    /**
     * The one endpoint that intentionally echoes the wallId back to the caller —
     * the SPA uses this to bootstrap its identity from the cookie.
     */
    static final String WALL_ID_ECHO_ENDPOINT = "/rest/wall-id";

    /**
     * Regex pattern matching stack-trace fragments and internal class names.
     *
     * <p>Matches:
     * <ul>
     *   <li>{@code Exception} or {@code Throwable} — type names leaked in error messages</li>
     *   <li>{@code java.lang.}, {@code java.io.} etc. — JDK package prefix</li>
     *   <li>{@code de.seism0saurus.} — Glacier internal package prefix</li>
     *   <li>{@code at ClassName.method(FileName.java:123)} — stack frame format</li>
     * </ul>
     *
     * <p>ASVS V11.1.4 (L1): application must not expose stack traces to the client.
     */
    static final Pattern STACK_TRACE_PATTERN = Pattern.compile(
            "Exception|Throwable|java\\.\\w+\\.|de\\.seism0saurus\\.|at \\w[\\w.$]*\\(.*\\.java:\\d+\\)");

    // -------------------------------------------------------------------------
    // Helper: common assertions run against every endpoint response
    // -------------------------------------------------------------------------

    /**
     * Assert that the response body does NOT contain the canary wallId, UNLESS the
     * endpoint is the intentional echo endpoint {@code /rest/wall-id}.
     *
     * @param path         the request path tested
     * @param responseBody the response body string (may be empty for 204 etc.)
     */
    static void assertNoCanaryLeak(String path, String responseBody) {
        if (WALL_ID_ECHO_ENDPOINT.equals(path)) {
            // /rest/wall-id intentionally echoes the UUID — allowlisted (ADR-4)
            return;
        }
        assertThat(responseBody)
                .as("IT-sec-LEAK (SR-NEW-03, ADR-4, WSTG-INFO-05): "
                        + "response body for [%s] must not contain the canary wallId [%s]. "
                        + "The wallId is a session identifier; echoing it on other endpoints "
                        + "exposes the identity token unnecessarily.",
                        path, CANARY_WALL_ID)
                .doesNotContain(CANARY_WALL_ID);
    }

    /**
     * Assert that the response body does NOT contain stack-trace patterns or internal class names.
     *
     * @param path         the request path tested
     * @param responseBody the response body string (may be empty)
     */
    static void assertNoStackTrace(String path, String responseBody) {
        if (responseBody == null || responseBody.isEmpty()) {
            return; // empty body is fine
        }
        assertThat(STACK_TRACE_PATTERN.matcher(responseBody).find())
                .as("IT-sec-LEAK (SR-NEW-05, ASVS V11.1.4, WSTG-ERRH-01): "
                        + "response body for [%s] must not contain stack traces or internal class names. "
                        + "Actual body excerpt: [%.300s]",
                        path, responseBody)
                .isFalse();
    }

    // -------------------------------------------------------------------------
    // Helper: issue a GET with canary cookie and return the response body
    // -------------------------------------------------------------------------

    static MvcResult performGet(MockMvc mockMvc, String path) throws Exception {
        return mockMvc.perform(
                get(path)
                        .cookie(new Cookie("wallId", CANARY_WALL_ID))
                        .accept(MediaType.APPLICATION_JSON, MediaType.ALL))
                .andReturn();
    }

    // -------------------------------------------------------------------------
    // Mode 1: LIVE (default — fallback enabled, HTTPS cookies)
    // -------------------------------------------------------------------------

    /**
     * IT-sec-LEAK-live: secret-leak assertions in live mode (default configuration).
     *
     * <p>Mode: live — WebSocket active, {@code glacier.fallback.enabled=true} (default),
     * {@code glacier.cookie.secure=true} (default).
     */
    @Nested
    @SpringBootTest
    @AutoConfigureMockMvc
    @TestPropertySource(properties = {
            "glacier.fallback.enabled=true",
            "glacier.cookie.secure=true",
            "glacier.cache.maxHashtagsPerPrincipal=10",
            "glacier.fallback.ratelimit.perMinute=30",
            "glacier.fallback.ratelimit.perMinutePerIp=120",
            "glacier.ratelimit.eviction.intervalMs=600000",
            "glacier.domain=example.com",
            "glacier.share.host=share.example.com"
    })
    class LiveMode {

        @Autowired
        private MockMvc mockMvc;

        @MockitoBean
        @SuppressWarnings("unused")
        private MastodonClient mastodonClient;

        @ParameterizedTest(name = "live: no canary echo from {0}")
        @ValueSource(strings = {
                "/rest/wall-id",            // allowlisted — intentionally echoes UUID
                "/rest/mastodon-handle",
                "/rest/operator",
                "/rest/messages",
                "/rest/share-links",
                "/rest/share-csrf",
                "/rest/share/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/catalog",
                "/rest/share/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/messages",
                "/rest/share/img-proxy"
        })
        void liveMode_noCanaryLeak_inGetEndpoints(String path) throws Exception {
            MvcResult result = performGet(mockMvc, path);
            String body = result.getResponse().getContentAsString();
            assertNoCanaryLeak(path, body);
            assertNoStackTrace(path, body);
        }

        @ParameterizedTest(name = "live: no canary echo from non-GET {0}")
        @ValueSource(strings = {
                "/rest/share-links",
                "/rest/share-links/00000000-0000-0000-0000-000000000002"
        })
        void liveMode_noCanaryLeak_inNonGetEndpoints(String path) throws Exception {
            // Non-GET endpoints must not echo the canary wallId in their error bodies.
            // These paths return 4xx (CSRF failure, not-found, etc.) but must not leak the identity.
            String[] parts = path.split("/");
            boolean isDelete = parts[parts.length - 1].matches(
                    "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}");
            MvcResult result;
            if (isDelete) {
                result = mockMvc.perform(
                        delete(path)
                                .cookie(new Cookie("wallId", CANARY_WALL_ID))
                                .accept(MediaType.APPLICATION_JSON, MediaType.ALL))
                        .andReturn();
            } else {
                result = mockMvc.perform(
                        post(path)
                                .cookie(new Cookie("wallId", CANARY_WALL_ID))
                                .accept(MediaType.APPLICATION_JSON, MediaType.ALL))
                        .andReturn();
            }
            String body = result.getResponse().getContentAsString();
            assertNoCanaryLeak(path, body);
            assertNoStackTrace(path, body);
        }

        @Test
        void liveMode_wallIdEndpoint_doesEchoCanaryIntentionally() throws Exception {
            // Sanity check: /rest/wall-id DOES return the UUID (it reads from cookie)
            // This proves the canary detection would fire if it leaked from other endpoints
            MvcResult result = performGet(mockMvc, WALL_ID_ECHO_ENDPOINT);
            String body = result.getResponse().getContentAsString();
            // /rest/wall-id returns existing cookie value when cookie is present
            // (the canary is in the cookie so the response echoes it — this is the allowlisted path)
            assertThat(body).contains(CANARY_WALL_ID);
        }
    }

    // -------------------------------------------------------------------------
    // Mode 2: FALLBACK (glacier.fallback.enabled=true explicit)
    // -------------------------------------------------------------------------

    /**
     * IT-sec-LEAK-fallback: secret-leak assertions in fallback mode.
     *
     * <p>Mode: fallback — HTTP polling active, WebSocket may be unavailable.
     * {@code glacier.fallback.enabled=true} is the same as live-mode default, but here
     * we explicitly assert it to cover the fallback code path focus.
     */
    @Nested
    @SpringBootTest
    @AutoConfigureMockMvc
    @TestPropertySource(properties = {
            "glacier.fallback.enabled=true",
            "glacier.cookie.secure=true",
            "glacier.cache.maxHashtagsPerPrincipal=10",
            "glacier.fallback.ratelimit.perMinute=30",
            "glacier.fallback.ratelimit.perMinutePerIp=120",
            "glacier.ratelimit.eviction.intervalMs=600000",
            "glacier.domain=example.com",
            "glacier.share.host=share.example.com"
    })
    class FallbackMode {

        @Autowired
        private MockMvc mockMvc;

        @MockitoBean
        @SuppressWarnings("unused")
        private MastodonClient mastodonClient;

        @ParameterizedTest(name = "fallback: no canary echo from {0}")
        @ValueSource(strings = {
                "/rest/wall-id",
                "/rest/mastodon-handle",
                "/rest/operator",
                "/rest/messages",
                "/rest/share-links",
                "/rest/share-csrf",
                "/rest/share/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/catalog",
                "/rest/share/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/messages",
                "/rest/share/img-proxy"
        })
        void fallbackMode_noCanaryLeak_inGetEndpoints(String path) throws Exception {
            MvcResult result = performGet(mockMvc, path);
            String body = result.getResponse().getContentAsString();
            assertNoCanaryLeak(path, body);
            assertNoStackTrace(path, body);
        }

        @ParameterizedTest(name = "fallback: no canary echo from non-GET {0}")
        @ValueSource(strings = {
                "/rest/share-links",
                "/rest/share-links/00000000-0000-0000-0000-000000000002"
        })
        void fallbackMode_noCanaryLeak_inNonGetEndpoints(String path) throws Exception {
            String[] parts = path.split("/");
            boolean isDelete = parts[parts.length - 1].matches(
                    "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}");
            MvcResult result;
            if (isDelete) {
                result = mockMvc.perform(
                        delete(path)
                                .cookie(new Cookie("wallId", CANARY_WALL_ID))
                                .accept(MediaType.APPLICATION_JSON, MediaType.ALL))
                        .andReturn();
            } else {
                result = mockMvc.perform(
                        post(path)
                                .cookie(new Cookie("wallId", CANARY_WALL_ID))
                                .accept(MediaType.APPLICATION_JSON, MediaType.ALL))
                        .andReturn();
            }
            String body = result.getResponse().getContentAsString();
            assertNoCanaryLeak(path, body);
            assertNoStackTrace(path, body);
        }

        @Test
        void fallbackMode_messagesEndpoint_noStackTraceOnMissingHashtag() throws Exception {
            // Hit /rest/messages without a hashtag param — should get 400, not a stack trace
            MvcResult result = mockMvc.perform(
                    get("/rest/messages")
                            .cookie(new Cookie("wallId", CANARY_WALL_ID))
                            .accept(MediaType.APPLICATION_JSON))
                    .andReturn();
            String body = result.getResponse().getContentAsString();
            assertNoStackTrace("/rest/messages?[no hashtag]", body);
            assertNoCanaryLeak("/rest/messages", body);
        }
    }

    // -------------------------------------------------------------------------
    // Mode 3: KILLSWITCH (glacier.fallback.enabled=false)
    // -------------------------------------------------------------------------

    /**
     * IT-sec-LEAK-killswitch: secret-leak assertions in killswitch mode.
     *
     * <p>Mode: killswitch — {@code glacier.fallback.enabled=false}. The fallback controller
     * must respond with 404 (not 200), but must NOT expose stack traces.
     */
    @Nested
    @SpringBootTest
    @AutoConfigureMockMvc
    @TestPropertySource(properties = {
            "glacier.fallback.enabled=false",
            "glacier.cookie.secure=true",
            "glacier.cache.maxHashtagsPerPrincipal=10",
            "glacier.fallback.ratelimit.perMinute=30",
            "glacier.fallback.ratelimit.perMinutePerIp=120",
            "glacier.ratelimit.eviction.intervalMs=600000",
            "glacier.domain=example.com",
            "glacier.share.host=share.example.com"
    })
    class KillswitchMode {

        @Autowired
        private MockMvc mockMvc;

        @MockitoBean
        @SuppressWarnings("unused")
        private MastodonClient mastodonClient;

        @ParameterizedTest(name = "killswitch: no canary echo from {0}")
        @ValueSource(strings = {
                "/rest/wall-id",
                "/rest/mastodon-handle",
                "/rest/operator",
                "/rest/messages",    // 404 in killswitch — but must not leak stack traces
                "/rest/share-links",
                "/rest/share-csrf",
                "/rest/share/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/catalog",
                "/rest/share/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/messages",
                "/rest/share/img-proxy"
        })
        void killswitchMode_noCanaryLeak_inGetEndpoints(String path) throws Exception {
            MvcResult result = performGet(mockMvc, path);
            String body = result.getResponse().getContentAsString();
            assertNoCanaryLeak(path, body);
            assertNoStackTrace(path, body);
        }

        @ParameterizedTest(name = "killswitch: no canary echo from non-GET {0}")
        @ValueSource(strings = {
                "/rest/share-links",
                "/rest/share-links/00000000-0000-0000-0000-000000000002"
        })
        void killswitchMode_noCanaryLeak_inNonGetEndpoints(String path) throws Exception {
            String[] parts = path.split("/");
            boolean isDelete = parts[parts.length - 1].matches(
                    "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}");
            MvcResult result;
            if (isDelete) {
                result = mockMvc.perform(
                        delete(path)
                                .cookie(new Cookie("wallId", CANARY_WALL_ID))
                                .accept(MediaType.APPLICATION_JSON, MediaType.ALL))
                        .andReturn();
            } else {
                result = mockMvc.perform(
                        post(path)
                                .cookie(new Cookie("wallId", CANARY_WALL_ID))
                                .accept(MediaType.APPLICATION_JSON, MediaType.ALL))
                        .andReturn();
            }
            String body = result.getResponse().getContentAsString();
            assertNoCanaryLeak(path, body);
            assertNoStackTrace(path, body);
        }

        @Test
        void killswitchMode_messagesEndpoint_returns404WithoutStackTrace() throws Exception {
            // In killswitch mode, /rest/messages must return 404 without leaking internals.
            // Provide a valid hashtag param so parameter binding doesn't reject before
            // the controller's kill-switch check runs (Spring MVC validates @RequestParam
            // before the method body executes, so 400 would fire without a hashtag param).
            MvcResult result = mockMvc.perform(
                    get("/rest/messages")
                            .param("hashtag", "testtag")
                            .cookie(new Cookie("wallId", CANARY_WALL_ID))
                            .accept(MediaType.APPLICATION_JSON))
                    .andReturn();
            int status = result.getResponse().getStatus();
            String body = result.getResponse().getContentAsString();

            assertThat(status)
                    .as("IT-sec-LEAK-killswitch: /rest/messages must return 404 when fallback disabled "
                            + "(glacier.fallback.enabled=false). Actual status: %d. "
                            + "Body: [%.200s]", status, body)
                    .isEqualTo(404);
            assertNoStackTrace("/rest/messages [killswitch]", body);
            assertNoCanaryLeak("/rest/messages", body);
        }
    }

    // -------------------------------------------------------------------------
    // Mode 4: INSECURE TRANSPORT (glacier.cookie.secure=false)
    // -------------------------------------------------------------------------

    /**
     * IT-sec-LEAK-insecure: secret-leak assertions in insecure-transport mode.
     *
     * <p>Mode: insecure-transport — {@code glacier.cookie.secure=false}. The cookie Secure
     * flag is absent, enabling HTTP transport for dev/non-TLS environments. The secret-leak
     * assertions must hold in this mode too (SR-NEW-05, ADR-5).
     */
    @Nested
    @SpringBootTest
    @AutoConfigureMockMvc
    @TestPropertySource(properties = {
            "glacier.fallback.enabled=true",
            "glacier.cookie.secure=false",   // insecure-transport mode (HTTP, dev/test)
            "glacier.cache.maxHashtagsPerPrincipal=10",
            "glacier.fallback.ratelimit.perMinute=30",
            "glacier.fallback.ratelimit.perMinutePerIp=120",
            "glacier.ratelimit.eviction.intervalMs=600000",
            "glacier.domain=example.com",
            "glacier.share.host=share.example.com"
    })
    class InsecureTransportMode {

        @Autowired
        private MockMvc mockMvc;

        @MockitoBean
        @SuppressWarnings("unused")
        private MastodonClient mastodonClient;

        @ParameterizedTest(name = "insecure-transport: no canary echo from {0}")
        @ValueSource(strings = {
                "/rest/wall-id",
                "/rest/mastodon-handle",
                "/rest/operator",
                "/rest/messages",
                "/rest/share-links",
                "/rest/share-csrf",
                "/rest/share/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/catalog",
                "/rest/share/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/messages",
                "/rest/share/img-proxy"
        })
        void insecureTransportMode_noCanaryLeak_inGetEndpoints(String path) throws Exception {
            MvcResult result = performGet(mockMvc, path);
            String body = result.getResponse().getContentAsString();
            assertNoCanaryLeak(path, body);
            assertNoStackTrace(path, body);
        }

        @ParameterizedTest(name = "insecure-transport: no canary echo from non-GET {0}")
        @ValueSource(strings = {
                "/rest/share-links",
                "/rest/share-links/00000000-0000-0000-0000-000000000002"
        })
        void insecureTransportMode_noCanaryLeak_inNonGetEndpoints(String path) throws Exception {
            String[] parts = path.split("/");
            boolean isDelete = parts[parts.length - 1].matches(
                    "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}");
            MvcResult result;
            if (isDelete) {
                result = mockMvc.perform(
                        delete(path)
                                .cookie(new Cookie("wallId", CANARY_WALL_ID))
                                .accept(MediaType.APPLICATION_JSON, MediaType.ALL))
                        .andReturn();
            } else {
                result = mockMvc.perform(
                        post(path)
                                .cookie(new Cookie("wallId", CANARY_WALL_ID))
                                .accept(MediaType.APPLICATION_JSON, MediaType.ALL))
                        .andReturn();
            }
            String body = result.getResponse().getContentAsString();
            assertNoCanaryLeak(path, body);
            assertNoStackTrace(path, body);
        }

        @Test
        void insecureTransportMode_malformedShareId_noStackTrace() throws Exception {
            // Attempt to access a share catalog with a malformed ID — must not return stack trace
            MvcResult result = mockMvc.perform(
                    get("/rest/share/<script>alert(1)</script>/catalog")
                            .cookie(new Cookie("wallId", CANARY_WALL_ID))
                            .accept(MediaType.APPLICATION_JSON))
                    .andReturn();
            String body = result.getResponse().getContentAsString();
            assertNoStackTrace("/rest/share/[malformed]/catalog", body);
            // The malformed ID must not appear in the response (input reflection prevention)
            assertThat(body)
                    .as("Malformed share ID must not be reflected in response body (XSS, WSTG-INPV-01)")
                    .doesNotContain("<script>");
        }
    }
}
