name: "Verify the code"

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Get cache for local Maven repository
        uses: actions/cache/restore@v4
        with:
          path: ~/.m2/repository
          key: maven-verify
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.13.0
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: npm dependencies and Angular cli
        run: npm install -g @angular/cli@17
      - name: Verify the webapp
        run: mvn --batch-mode --update-snapshots verify --file pom.xml
